### ISSUE TITLE
Is it possible to use this as a shared TestData source ?

### ISSUE THREAD

**Issue by ipleten** [launchdarkly/java-server-sdk-redis#17]
For each  integration testing we create isolated environments with all needed dependencies services.
Is it possible to use Redis  as a testdata source to change flags which are used only be those dependent services?
So we want to do integration test for  service "A"  dynamically changing flags for service "B"-"D" via shared Redis in to cover all possible code paths.

**Comment by louis-launchdarkly** [comment]
Hello @ipleten, thank you for reaching out. Unfortunately, the Redis integration cannot be used as a shared TestData source, as the TestData source itself isn't an adaptor - the TestData source maintains its own HashMap of configured flag data.

Given the idea is to do integration tests with a changing set of flags, I would recommend using the [FIleData Source](https://github.com/launchdarkly/java-server-sdk/blob/main/src/main/java/com/launchdarkly/sdk/server/integrations/FileData.java) [docs](https://docs.launchdarkly.com/sdk/features/flags-from-files#java) - The FileData source supports auto-loading when the file changes, so you can even prepare multiple test cases and file ahead of time and use some scripts to change the file content to load new flags for testing.

**Comment by ipleten** [comment]
Thank you @louis-launchdarkly.
Yeah I've seen FileData but thought it might be more DB-ish way to handle this, as we are using kubernetes and ConfigMaps do not propagate files immediately to pods. 
Anyway thank you for your response.
